### ISSUE TITLE
Usage in ScrollViewer causes InvalidOperationException

### ISSUE THREAD

**Issue by roberthusak** [Oaz/AvaloniaGraphControl#6]
Hi, thanks for this great project 👍 I just have an issue when using it as a child of `ScrollViewer`, e.g. when modifying `MainWindow.xaml` in the sample the following way:
```
...
    </StackPanel>
    <ScrollViewer Grid.Column="0" Grid.Row="1">
      <agc:GraphPanel Background="WhiteSmoke" Graph="{Binding SelectedItem, ElementName=graphs}" Zoom="{Binding Value, ElementName=zoomer}" LayoutMethod="{Binding SelectedItem, ElementName=layoutMethods}">
...
      </agc:GraphPanel>
    </ScrollViewer>
  </Grid>
...
```

The following exception is thrown:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Invalid size returned for Measure.
  Source=Avalonia.Layout
  StackTrace:
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Presenters.ScrollContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
   at Avalonia.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
   at Avalonia.Controls.Grid.MeasureOverride(Size constraint)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness)
   at Avalonia.Controls.Border.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize)
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize)
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass(ILayoutRoot root)
   at Avalonia.Controls.Window.Show()
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvaloniaGraphControlSample.Program.Main(String[] args) in C:\iolevel\playground\AvaloniaGraphControl\sample\Program.cs:line 13
```

I'll attach a PR which should fix it.

**Comment by Oaz** [comment]
Thanks. Incidentally, the need for scroll view just popped up in my radar yesterday but I had not taken the time to look into it yet, so I really appreciate this PR.

**Comment by roberthusak** [comment]
Glad to help. I also noticed that inside a `ScrollViewer` there's a problem with graph zooming - basically, it doesn't respect the zoomed dimensions of the graph and places scrollbars according to the original size. I wasn't able to solve that though..

Btw. it seems that the graph control works well inside https://github.com/wieslawsoltes/PanAndZoom.

**Comment by Oaz** [comment]
You're right. Incidentally (again) I bumped into this issue this morning.
I updated the sample app using "LayoutTransformControl".
Actually, the Zoom property on the Panel was a very bad idea since it can be nicely managed from the outside.

**Comment by roberthusak** [comment]
Nice! It works great now.
